<a href="https://colab.research.google.com/github/R4HUL-ROY/Machine-Learning/blob/main/KNN_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ASSIGNMENT ON K-NN CLASSIFICATION**

**NAME : RAHUL ROY**

**MCA 2nd SEM**

**ROLL : C91/MCA/202032**

---------------------------------------------------------



In [ ]:
import numpy as np
import pandas as pd

**Choose dataset**

In [ ]:
# READ DATASET - 1
# irish dataset

from sklearn import datasets
myiris = datasets.load_iris()
# print(myiris)
x = myiris.data
y = myiris.target

In [ ]:
# READ DATASET - 2
# kaggle diabetes classification dataset
# link of this dataset https://www.kaggle.com/uciml/pima-indians-diabetes-database

df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/diabetes.csv')
print(df.shape)

data_df = df[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']]

result_df = df['Outcome']       

x = np.array(data_df)
y = np.array(result_df)


(768, 9)


In [ ]:
# READ DATASET - 3
# Breast Cancer Wisconsin (Diagnostic) Data Set
# link for this dataset  https://www.kaggle.com/uciml/breast-cancer-wisconsin-data

df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/data.csv')
print(df.shape)

data_df = df[['radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst']]

result_df = df['diagnosis']

x = np.array(data_df)
y = np.array(result_df)


(569, 33)


In [ ]:
# READ DATASET 4
# winequality classifcation dataset

df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/winequality-red.csv')
print(df.shape)

data_df = df[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']]

result_df = df['quality']

x = np.array(data_df)
y = np.array(result_df)

(1599, 12)


In [ ]:
## DATASET - 5    // CATAGORICAL DATASET
# CAR DATASET    link : http://archive.ics.uci.edu/ml/datasets/Car+Evaluation


df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/car.csv')

## renaming the column names
col_name = ['buying', 'maint', 'doors' , 'persons', 'lug_boot', 'safety', 'class']
df.columns = col_name

data_df = df[['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety']]
result_df = df['class']

x = np.array(data_df)
y = np.array(result_df)

print(df.shape)
print(x.shape)
print(y.shape)

(1727, 7)
(1727, 6)
(1727,)


In [ ]:
df.head(5)

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    med  unacc
1  vhigh  vhigh     2       2    small   high  unacc
2  vhigh  vhigh     2       2      med    low  unacc
3  vhigh  vhigh     2       2      med    med  unacc
4  vhigh  vhigh     2       2      med   high  unacc

**SCALING THE FEATURES**

In [ ]:
## scaling the data between 0-1 (using MIN-MAX Scalling)

transpose_x = np.transpose(x)
tr_x_row, tr_x_col = transpose_x.shape
for i in range(tr_x_row):
  # finding max and min value for a particular column of originar dataset (row for the transposed matrix)
  max_val = np.max(transpose_x[i])   
  min_val = np.min(transpose_x[i])
  for j in range(transpose_x[i].shape[0]):
    transpose_x[i,j] = (transpose_x[i,j]-min_val)/(max_val - min_val) # MIN-MAX SCALLING

#x transposed again to get the dimension of original dataset
x = np.transpose(transpose_x)  


print(x)

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.19444444 0.58333333 0.08474576 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.16666667 0.45833333 0.08474576 0.        ]
 [0.30555556 0.70833333 0.08474576 0.04166667]
 [0.13888889 0.58333333 0.10169492 0.04166667]
 [0.13888889 0.41666667 0.06779661 0.        ]
 [0.         0.41666667 0.01694915 0.        ]
 [0.41666667 0.83333333 0.03389831 0.04166667]
 [0.38888889 1.         0.08474576 0.125     ]
 [0.30555556 0.79166667 0.05084746 0.125     ]
 [0.22222222 0.625      0.06779661 0.08333333]
 [0.38888889 0.75       0.11864407 0.08333333]
 [0.22222222 0.75       0.08474576 0.08333333]
 [0.30555556 0.58333333 0.11864407 0.04166667]
 [0.22222222 

**SPLITTING THE DATASET INTO TRAIN AND TEST**

In [ ]:
## splitting the actuall dataset into x_train, x_test , y_train and y_test
## splitting  80 : 20 ratio by generating random number

import random

row, col = x.shape
row_count_for_train = round(row*0.8)   # 80% selected as train data

train_rows = []   #containing the indexes of rows considered for training
test_rows = []    #containing the indexes of rows considered for testing 

while len(train_rows) < row_count_for_train:
  random_num = random.randint(0, row-1)  # generating random number
  if random_num not in train_rows:
    train_rows.append(random_num)

for i in range(row):
  if i not in train_rows:
    test_rows.append(i)
random.shuffle(test_rows)  #shuffling because our test_rows was containing value in sorted order    

x_train = x[train_rows,]
y_train = y[train_rows,]

x_test = x[test_rows,]
y_test = y[test_rows,]


**FIT THE MODEL AND PREDICT**

In [ ]:
## fit and predict from the model
import math
 
#finding maximum occured element from the list l
def classify(l):
  max_time_occured =  max(set(l), key = l.count)  # returns the maximum occured element from the list
  return max_time_occured
 
 
#this function takes all pair distance and pick k nearest  possible_prediction from them and pass to classify function
def predict(dist, x_train, y_train, k):
  sorted_dist = dist.copy()
  sorted_dist.sort() 
  possible_prediction_list = [] #possible classification for a test sample, containing k values, for k-NN 
 
  for i in range(k): #first k value of the sorted list be k nearest point
    index = dist.index(sorted_dist[i])
    possible_prediction_list.append(y_train[index])
  final_predicted_value = classify(possible_prediction_list) ##calling classify function which classify the test sample by finding most occured outcome from nearest k neighbours outcome
  return final_predicted_value
 
 
## eucledian distance
def eucledian_distance(row_x, row_y):
  return  np.sqrt(sum((row_x - row_y)**2))

## manhatten distance
def manhatten_distance(row_x, row_y):
  count = 0
  for i in range(row_x.shape[0]):
    if row_x[i] != row_y[i]:
      count += 1
  return count    


def fit_and_predict(x_train, y_train, x_test, k):
  y_pred = []  #containing the abosultely final result value (classification value for each test data sample)
  for this_test_row in range(len(x_test)): # iterate for each test row
    dist = []  #containing distance of each row in train data set from the test data row
    for i in range(x_train.shape[0]): # iterate over each row in train data  
      dist.append(eucledian_distance(x_train[i] , x_test[this_test_row] ))    # eucledian distance   
      # dist.append(manhatten_distance (x_train[i] , y_train[this_test_row] ))     # manhatten distance
    predicted_value = predict(dist, x_train, y_train, k) #calling predict function with the list containing all pairs distance to find nearest and classify result from them
    y_pred.append(predicted_value)
  y_pred = np.array(y_pred)
  return y_pred 
 


# def fit_and_predict(x_train, x_test, y_train, k):
#   y_pred = []  #containing the abosultely final result value (classification value for each test data sample)
#   for this_test_row in range(len(y_train)): # iterate for each test row
#     dist = []  #containing distance of each row in train data set from the test data row
#     for i in range(x_train.shape[0]): # iterate over each row in train data 
#       total = 0
#       for j in range(x_train.shape[1]): #iterate over each features one by one
#         total += (x_train[i, j] - y_train[this_test_row,j])**2   #eucledian distance formula sqrt(sum((xi-yi)^2)) # i denotes ith column
#       dist.append(math.sqrt(total))  
#     predicted_value = predict(dist, x_train, x_test, k) #calling predict function with the list containing all pairs distance to find nearest and classify result from them
#     y_pred.append(predicted_value)
#   y_pred = np.array(y_pred)
#   return y_pred
 
## result for single k value
# k = int(input("enter the value of k  (number of nearest members to consider), for K-NN : "))
# y_predicted = fit_and_predict(x_train, x_test, y_train, k)

**SEE RESULT OF THE K-NN MODEL**

FOR EXAMPLE **input should be 3** if you want to see the **result only for K value 3**
 
to see result **for multiple k value input should be two comma separated integer**  **EXAMPLE:** **1,5** will show the result of k value **from 1 to 5 separately**

In [ ]:
## see result for single k value or multiple k value

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

#taking input of k value from the user
k_value = input("enter single value of k or a range of k(comma separated) : ").split(',')
lower = k_value[0]
if len(k_value) == 1:
  upper = k_value[0]
else:
  upper = k_value[1]
lower,upper = int(lower), int(upper)  

for k in range(lower,upper+1):   # iterate over different k value if user provides a range of k (lower and upper is same in case user provides one single value as input)
  y_predicted = fit_and_predict(x_train, y_train, x_test, k)  # call for prediction for a single k value
  matrix = confusion_matrix(y_test, y_predicted)
  diagonal_sum = 0
  total_sum = 0

  #calculating diagonal sum and total sum from confusion matrix
  for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
      if i == j:
        diagonal_sum += matrix[i,j]
      total_sum += matrix[i,j]

  print(f"\nvalue of k = {k} \n Accuracy = {(diagonal_sum/total_sum)*100}%")   # accuracy coressponding to k value
  print(f"\nconfusuin matrix :\n {matrix}\n\n")
  from sklearn.metrics import classification_report
  print(f"{classification_report(y_test, y_predicted)}" )
  print("__________________________________________________________________________") 


enter single value of k or a range of k(comma separated) : 1,9

value of k = 1 
 Accuracy = 93.85964912280701%

confusuin matrix :
 [[71  4]
 [ 3 36]]


              precision    recall  f1-score   support

           B       0.96      0.95      0.95        75
           M       0.90      0.92      0.91        39

    accuracy                           0.94       114
   macro avg       0.93      0.93      0.93       114
weighted avg       0.94      0.94      0.94       114

__________________________________________________________________________

value of k = 2 
 Accuracy = 97.36842105263158%

confusuin matrix :
 [[75  0]
 [ 3 36]]


              precision    recall  f1-score   support

           B       0.96      1.00      0.98        75
           M       1.00      0.92      0.96        39

    accuracy                           0.97       114
   macro avg       0.98      0.96      0.97       114
weighted avg       0.97      0.97      0.97       114

____________________________